export const remoteEntryCopy = {
  "zh-CN": {
    codeInstructions:
      "开启远程访问后，用手机扫码并输入授权码即可连接，无需再次确认。关闭窗口后可继续运行；完全退出或关机将停止访问。",
    legacyPermissions: "旧版浏览器授权范围",
    legacyPermissionsHint:
      "以下执行开关与工作区选择仅影响旧版授权；新授权码已包含全部 AgentKib 工作区与当前支持的远控操作。工作区外目录仍需在下方单独添加。",
    manualAccess:
      "本机或手动配置访问：未验证公网可达。请自行确认 HTTPS 反向代理配置与访问地址；此配对码不表示公网连接就绪。",
    saveFailed: "设置保存失败，请检查磁盘权限与空间后重试。",
    startFailed: "本机服务启动失败，请检查高级连接设置后重试。",
    switchWarning:
      "更换桥接服务会停止旧连接并清除本机浏览器授权，需要重新扫码配对。旧服务凭证不会转移。",
    remoteTitle: "远程连接",
    instructions:
      "开启远程访问后，用手机扫码并在此确认授权。关闭窗口后可继续运行；完全退出或关机将停止访问。",
    advanced: "高级连接与权限设置",
    broker: "桥接服务地址（官方或自建）",
    frpc: "自定义 frpc 程序路径（选填）",
    bundled: "默认使用内置程序",
    frpcHint: "自定义程序必须与当前平台的内置 frpc 内容相同；启动前会校验 SHA-256。",
    exitCode: "进程退出码",
    exitSignal: "进程终止信号",
    bandwidth: "预览总带宽（KiB/s，保存设置后生效）",
    invitation: "邀请码（首次连接时填写）",
    enable: "开启远程访问",
    enabledRemote: "远程访问已开启",
    reenroll: "使用新邀请码重新登记设备",
    pause: "暂停公网访问",
    pauseHint: "暂停公网访问或撤销手机不会自动终止 Codex 后台任务。",
    control: "控制通道",
    preview: "预览通道",
    certificateWarning: "证书续期暂未成功，将自动重试；当前证书仍有效。",
    scan: "手机扫码访问",
    pendingPhone: "待确认手机授权",
    workspaces: "允许远程管理任务和读取文件的工作区",
    newPermissions: "新权限默认关闭。已有设备需要重新配对后授权。",
    extraRoots: "额外只读目录（每行一个绝对路径）",
    migrationNotice:
      "官方连接服务地址已调整。请使用新邀请码确认迁移到新的官方连接服务；旧凭证不会转移，迁移时将停止旧连接。",
    prepareMigration: "准备迁移官方连接",
    confirmMigration: "确认迁移并开启远程访问",
    nativeTitle: "连接其他电脑",
    nativeDescription: "通过 AgentKib 桌面发现、配对和连接其他电脑，与手机浏览器授权分别管理。",
    lanAdvanced: "局域网访问（高级）",
    lanRunning: "局域网 HTTP 访问正在运行",
    lanUnavailable: "局域网访问已开启但暂不可用",
    lanManage: "管理局域网访问",
    phases: {
      disabled: "尚未开启远程访问",
      registering: "正在登记电脑",
      certifying: "正在准备安全连接",
      connecting: "正在连接",
      ready: "可供手机连接",
      offline: "连接中断",
      error: "连接失败",
    },
    reasons: {
      revoked: "设备授权已撤销，请输入新邀请码重新登记",
      "lease-expired": "授权租约已过期，公网访问已关闭",
      network: "暂时无法连接服务，将自动重试",
      certificate: "证书不可用或校验未通过",
      connector: "连接程序暂不可用，将自动重试",
      suspended: "电脑休眠期间暂停远控访问",
      setup: "请检查连接配置和设备登记状态",
    },
    failureStages: {
      broker: "管理服务",
      certificate: "证书",
      "control-connector": "控制通道",
      "preview-connector": "预览通道",
      "control-probe": "控制地址公网探测",
      "preview-probe": "预览地址公网探测",
    },
    failureCodes: {
      dns: "域名解析失败",
      timeout: "连接超时",
      tls: "TLS 校验失败",
      http: "服务返回错误",
      process: "连接程序退出",
      identity: "服务身份校验失败",
      unreachable: "网络不可达或连接被中断",
      unknown: "连接失败",
      integrity: "frpc 校验失败，请使用与内置程序相同的文件",
      conflict: "通道名称已被占用",
    },
    retryAt: "下次重试：",
  },
  "zh-TW": {
    codeInstructions:
      "開啟遠端存取後，用手機掃碼並輸入授權碼即可連線，無需再次確認。關閉視窗後可繼續執行；完全結束或關機將停止存取。",
    legacyPermissions: "舊版瀏覽器授權範圍",
    legacyPermissionsHint:
      "以下執行開關與工作區選擇僅影響舊版授權；新授權碼已包含全部 AgentKib 工作區與目前支援的遠端操作。工作區外目錄仍需在下方個別新增。",
    manualAccess:
      "本機或手動設定存取：未驗證公網可達。請自行確認 HTTPS 反向代理設定與存取位址；此配對碼不表示公網連線就緒。",
    saveFailed: "設定儲存失敗，請檢查磁碟權限與空間後重試。",
    startFailed: "本機服務啟動失敗，請檢查進階連線設定後重試。",
    switchWarning:
      "更換橋接服務會停止舊連線並清除本機瀏覽器授權，需要重新掃碼配對。舊服務憑證不會移轉。",
    remoteTitle: "遠端連線",
    instructions:
      "開啟遠端存取後，用手機掃碼並在此確認授權。關閉視窗後可繼續執行；完全結束或關機將停止存取。",
    advanced: "進階連線與權限設定",
    broker: "橋接服務位址（官方或自建）",
    frpc: "自訂 frpc 程式路徑（選填）",
    bundled: "預設使用內建程式",
    frpcHint: "自訂程式必須與目前平台的內建 frpc 內容相同；啟動前會校驗 SHA-256。",
    exitCode: "進程退出碼",
    exitSignal: "進程終止訊號",
    bandwidth: "預覽總頻寬（KiB/s，儲存設定後生效）",
    invitation: "邀請碼（首次連線時填寫）",
    enable: "開啟遠端存取",
    enabledRemote: "遠端存取已開啟",
    reenroll: "使用新邀請碼重新登記裝置",
    pause: "暫停公網存取",
    pauseHint: "暫停公網存取或撤銷手機不會自動終止 Codex 背景任務。",
    control: "控制通道",
    preview: "預覽通道",
    certificateWarning: "憑證續期暫未成功，將自動重試；目前憑證仍有效。",
    scan: "手機掃碼存取",
    pendingPhone: "待確認手機授權",
    workspaces: "允許遠端管理任務和讀取檔案的工作區",
    newPermissions: "新權限預設關閉。既有裝置需要重新配對後授權。",
    extraRoots: "額外唯讀目錄（每行一個絕對路徑）",
    migrationNotice:
      "官方連線服務位址已調整。請使用新邀請碼確認移轉至新的官方連線服務；舊憑證不會移轉，移轉時將停止舊連線。",
    prepareMigration: "準備移轉官方連線",
    confirmMigration: "確認移轉並開啟遠端存取",
    nativeTitle: "連接其他電腦",
    nativeDescription: "透過 AgentKib 桌面探索、配對和連接其他電腦，與手機瀏覽器授權分開管理。",
    lanAdvanced: "區域網路存取（進階）",
    lanRunning: "區域網路 HTTP 存取正在執行",
    lanUnavailable: "區域網路存取已開啟但暫不可用",
    lanManage: "管理區域網路存取",
    phases: {
      disabled: "尚未開啟遠端存取",
      registering: "正在登記電腦",
      certifying: "正在準備安全連線",
      connecting: "正在連線",
      ready: "可供手機連線",
      offline: "連線中斷",
      error: "連線失敗",
    },
    reasons: {
      revoked: "裝置授權已撤銷，請輸入新邀請碼重新登記",
      "lease-expired": "授權租約已過期，公網存取已關閉",
      network: "暫時無法連接服務，將自動重試",
      certificate: "憑證不可用或驗證未通過",
      connector: "連線程式暫不可用，將自動重試",
      suspended: "電腦休眠期間暫停遠端存取",
      setup: "請檢查連線設定和裝置登記狀態",
    },
    failureStages: {
      broker: "管理服務",
      certificate: "憑證",
      "control-connector": "控制通道",
      "preview-connector": "預覽通道",
      "control-probe": "控制位址公開探測",
      "preview-probe": "預覽位址公開探測",
    },
    failureCodes: {
      dns: "網域解析失敗",
      timeout: "連線逾時",
      tls: "TLS 驗證失敗",
      http: "服務回應錯誤",
      process: "連線程式已結束",
      identity: "服務身分驗證失敗",
      unreachable: "網路無法到達或連線中斷",
      unknown: "連線失敗",
      integrity: "frpc 校驗失敗，請使用與內建程式相同的檔案",
      conflict: "通道名稱已被占用",
    },
    retryAt: "下次重試：",
  },
  "en-US": {
    codeInstructions:
      "Enable remote access, scan with your phone and enter the access code to connect without another confirmation. Closing the window keeps access running; quitting the app or shutting down stops access.",
    legacyPermissions: "Legacy browser permissions",
    legacyPermissionsHint:
      "These control and workspace settings apply only to legacy grants. New access codes include all AgentKib workspaces and currently supported remote operations. Add directories outside workspaces separately below.",
    manualAccess:
      "Local or manually configured access: public reachability is not verified. Check your HTTPS reverse proxy and access address. A pairing code does not mean public access is ready.",
    saveFailed: "Settings could not be saved. Check disk permissions and space, then retry.",
    startFailed: "The local service could not start. Check advanced connection settings and retry.",
    switchWarning:
      "Changing bridge service stops the old connection and clears browser grants. Pair your phone again; old service credentials are not transferred.",
    remoteTitle: "Remote connection",
    instructions:
      "Enable remote access, scan with your phone, then authorize it here. Closing the window keeps access running; quitting the app or shutting down stops access.",
    advanced: "Advanced connection and permissions",
    broker: "Bridge service (official or self-hosted)",
    frpc: "Custom frpc executable (optional)",
    bundled: "Use bundled connector",
    frpcHint:
      "A custom executable must match the bundled frpc for this platform; SHA-256 is checked before launch.",
    exitCode: "Process exit code",
    exitSignal: "Process termination signal",
    bandwidth: "Preview bandwidth (KiB/s; save settings to apply)",
    invitation: "Invitation (first connection only)",
    enable: "Enable remote access",
    enabledRemote: "Remote access is enabled",
    reenroll: "Register again with new invitation",
    pause: "Pause public access",
    pauseHint: "Pausing public access or revoking a phone does not stop Codex background tasks.",
    control: "Control",
    preview: "Preview",
    certificateWarning: "Certificate renewal will retry; the current certificate is still valid.",
    scan: "Open on your phone",
    pendingPhone: "Phone authorization pending",
    workspaces: "Workspaces for task management and file access",
    newPermissions: "New permissions default to off. Re-pair existing devices to grant them.",
    extraRoots: "Additional read-only directories (one absolute path per line)",
    migrationNotice:
      "The official connection service address has changed. Confirm migration with a new invitation. Old credentials are not transferred and the old connection will stop.",
    prepareMigration: "Prepare service migration",
    confirmMigration: "Confirm migration and enable access",
    nativeTitle: "Connect to another computer",
    nativeDescription:
      "Discover, pair and connect with another AgentKib desktop. These permissions are separate from phone browser access.",
    lanAdvanced: "LAN access (advanced)",
    lanRunning: "LAN HTTP access is running",
    lanUnavailable: "LAN access is enabled but unavailable",
    lanManage: "Manage LAN access",
    phases: {
      disabled: "Remote access is off",
      registering: "Registering computer",
      certifying: "Preparing secure connection",
      connecting: "Connecting",
      ready: "Ready for your phone to connect",
      offline: "Connection interrupted",
      error: "Connection failed",
    },
    reasons: {
      revoked: "Device authorization revoked; register with a new invitation",
      "lease-expired": "Authorization expired; public access closed",
      network: "Service unavailable; retrying automatically",
      certificate: "Certificate unavailable or invalid",
      connector: "Connector unavailable; retrying automatically",
      suspended: "Remote access paused while this computer sleeps",
      setup: "Check connection settings and device registration",
    },
    failureStages: {
      broker: "Management service",
      certificate: "Certificate",
      "control-connector": "Control connector",
      "preview-connector": "Preview connector",
      "control-probe": "Control public probe",
      "preview-probe": "Preview public probe",
    },
    failureCodes: {
      dns: "DNS lookup failed",
      timeout: "Connection timed out",
      tls: "TLS validation failed",
      http: "Service returned an error",
      process: "Connector exited",
      identity: "Service identity check failed",
      unreachable: "Network unreachable or connection interrupted",
      unknown: "Connection failed",
      integrity: "frpc verification failed; use a file identical to the bundled connector",
      conflict: "Proxy name already in use",
    },
    retryAt: "Next retry:",
  },
  "ja-JP": {
    codeInstructions:
      "リモートアクセスを有効にし、スマートフォンでスキャンして認証コードを入力すると、追加の確認なしで接続できます。ウィンドウを閉じても継続します。アプリの終了や電源オフで停止します。",
    legacyPermissions: "旧ブラウザーの権限範囲",
    legacyPermissionsHint:
      "以下の操作とワークスペース設定は旧認証のみに適用されます。新しい認証コードでは全 AgentKib ワークスペースと現在対応するリモート操作が許可されます。ワークスペース外のディレクトリは下で個別に追加してください。",
    manualAccess:
      "ローカルまたは手動設定でのアクセスです。インターネットからの到達性は未確認です。HTTPS リバースプロキシとアクセス先を確認してください。ペアリングコードは公開接続の準備完了を意味しません。",
    saveFailed: "設定を保存できません。ディスクの権限と空き容量を確認して再試行してください。",
    startFailed: "ローカルサービスを起動できません。接続の詳細設定を確認して再試行してください。",
    switchWarning:
      "サービスを変更すると旧接続とブラウザーの許可が解除されます。再ペアリングが必要です。旧認証情報は転送されません。",
    remoteTitle: "リモート接続",
    instructions:
      "リモートアクセスを有効にし、スマートフォンでスキャンしてここで承認します。ウィンドウを閉じても継続します。アプリの終了や電源オフで停止します。",
    advanced: "接続と権限の詳細設定",
    broker: "ブリッジサービス（公式またはセルフホスト）",
    frpc: "frpc 実行ファイルのパス（任意）",
    bundled: "内蔵コネクターを使用",
    frpcHint:
      "カスタムプログラムは、このプラットフォームの内蔵 frpc と同一である必要があります。起動前に SHA-256 を検証します。",
    exitCode: "プロセス終了コード",
    exitSignal: "プロセス終了シグナル",
    bandwidth: "プレビュー帯域幅（KiB/s、保存後に適用）",
    invitation: "招待コード（初回接続時）",
    enable: "リモートアクセスを有効化",
    enabledRemote: "リモートアクセスは有効です",
    reenroll: "新しい招待コードで再登録",
    pause: "インターネット経由のアクセスを一時停止",
    pauseHint:
      "アクセスの一時停止や端末の取り消しでは Codex のバックグラウンドタスクは停止しません。",
    control: "操作チャネル",
    preview: "プレビューチャネル",
    certificateWarning: "証明書の更新を再試行します。現在の証明書は有効です。",
    scan: "スマートフォンでスキャン",
    pendingPhone: "スマートフォンの承認待ち",
    workspaces: "タスク管理とファイル閲覧を許可するワークスペース",
    newPermissions: "新しい権限は既定で無効です。既存端末への付与には再ペアリングが必要です。",
    extraRoots: "追加の読み取り専用ディレクトリ（1 行に 1 つの絶対パス）",
    migrationNotice:
      "公式接続サービスのアドレスが変更されました。新しい招待コードで移行を確認してください。旧認証情報は転送されず、旧接続は停止します。",
    prepareMigration: "公式接続の移行を準備",
    confirmMigration: "移行を確認してアクセスを有効化",
    nativeTitle: "別のコンピューターに接続",
    nativeDescription:
      "別の AgentKib デスクトップを検出・ペアリング・接続します。スマートフォンのブラウザー権限とは別に管理します。",
    lanAdvanced: "LAN アクセス（詳細）",
    lanRunning: "LAN HTTP アクセスは稼働中です",
    lanUnavailable: "LAN アクセスは有効ですが利用できません",
    lanManage: "LAN アクセスを管理",
    phases: {
      disabled: "リモートアクセスは無効です",
      registering: "コンピューターを登録中",
      certifying: "安全な接続を準備中",
      connecting: "接続中",
      ready: "スマートフォンを接続できます",
      offline: "接続が切断されました",
      error: "接続に失敗しました",
    },
    reasons: {
      revoked: "端末認証が取り消されました。新しい招待コードで登録してください",
      "lease-expired": "認証期限が切れ、公開アクセスは停止しました",
      network: "サービスに接続できません。自動的に再試行します",
      certificate: "証明書を利用できないか検証に失敗しました",
      connector: "コネクターを利用できません。自動的に再試行します",
      suspended: "スリープ中はリモートアクセスを一時停止します",
      setup: "接続設定と端末登録を確認してください",
    },
    failureStages: {
      broker: "管理サービス",
      certificate: "証明書",
      "control-connector": "操作チャネル",
      "preview-connector": "プレビューチャネル",
      "control-probe": "操作アドレスの公開確認",
      "preview-probe": "プレビューアドレスの公開確認",
    },
    failureCodes: {
      dns: "名前解決に失敗",
      timeout: "接続がタイムアウト",
      tls: "TLS 検証に失敗",
      http: "サービスがエラーを返しました",
      process: "コネクターが終了",
      identity: "サービスの識別情報を確認できません",
      unreachable: "ネットワークに到達できないか接続が切断されました",
      unknown: "接続に失敗",
      integrity: "frpc の検証に失敗しました。内蔵プログラムと同一のファイルを使用してください",
      conflict: "プロキシ名が既に使用されています",
    },
    retryAt: "次の再試行：",
  },
};
