export const webSettingsCopy = {
  "zh-CN": {
    generateAccess: "生成八位授权码",
    codeScope:
      "有效授权码无需桌面再次确认，即按所选档位授权全部 AgentKib 工作区：“只读”可查看会话历史与文件；“完整远控”另含任务控制、审批与上传。授权后可随时在下方调整档位或撤销。仅分享给可信设备。",
    fullAccess: "完整远控权限",
    readOnlyAccess: "只读（查看会话与文件）",
    accessLevel: "授权档位",
    acceptance: "本地隔离验收模式：控制仅限以下会话，不代表正式验收通过。",
    portError: "端口已被占用，请选择其他端口后保存。",
    unverified: "本构建尚未通过 Web 实验控制真实验收，发送与审批保持禁用。",
    title: "允许手机访问这台电脑",
    enabled: "启用本机 Web 服务",
    port: "端口",
    origin: "外部 HTTPS 地址",
    experimental: "启用实验控制（仍需分别授予浏览器权限）",
    save: "保存设置",
    generate: "生成八位配对码",
    scope:
      "历史读取包含全部已登记及以后新增的工作区。任务管理和文件读取另受所选工作区、目录及浏览器权限限制。",
    pending: "待确认浏览器",
    reviewLater: "稍后在远程设置中处理",
    reviewLaterHint: "关闭弹窗不会授权；请求仍可在远程设置中处理，过期后自动失效。",
    decisionFailed: "处理失败或请求已过期，请到远程设置查看最新状态。",
    devices: "已授权浏览器",
    verify: "请与浏览器核对校验数字",
    send: "允许发送",
    approve: "允许审批",
    manage: "允许新建与交接 Codex 任务",
    files: "允许查看授权目录与产物",
    attachments: "允许上传图片与文件",
    advancedControl: "允许运行中追加与原生队列",
    organize: "允许重命名及归档会话",
    settings: "允许修改任务模型与模式",
    extendedApproval: "允许原生扩展审批（含会话级及持久规则）",
    accept: "确认授权",
    reject: "拒绝",
    revoke: "撤销",
    empty: "暂无",
    running: "运行中",
    stopped: "已关闭",
    expires: "有效期至",
    loading: "正在读取 Web 设置…",
    unavailable: "Web 设置不可用",
    warning:
      "实验功能仅在通过验证的主机与会话上可用；停止僅表示中斷目前輪次，不保證背景命令已結束。",
    read: "历史读取",
  },
  "zh-TW": {
    generateAccess: "產生八位授權碼",
    codeScope:
      "有效授權碼無需桌面再次確認，即依所選等級授權全部 AgentKib 工作區：「唯讀」可查看對話紀錄與檔案；「完整遠端操作」另含任務控制、審批與上傳。授權後可隨時在下方調整等級或撤銷。僅分享給可信裝置。",
    fullAccess: "完整遠端操作權限",
    readOnlyAccess: "唯讀（查看對話與檔案）",
    accessLevel: "授權等級",
    acceptance: "本機隔離驗收模式：操作僅限以下對話，不代表正式驗收通過。",
    portError: "連接埠已被佔用，請選擇其他連接埠後儲存。",
    unverified: "此建置尚未通過 Web 實驗控制真實驗收，傳送與核准維持停用。",
    title: "允許手機存取這台電腦",
    enabled: "啟用本機 Web 服務",
    port: "連接埠",
    origin: "外部 HTTPS 位址",
    experimental: "啟用實驗控制（仍需分別授予瀏覽器權限）",
    save: "儲存設定",
    generate: "產生八位配對碼",
    scope:
      "歷史讀取包含全部已登記及以後新增的工作區。任務管理和檔案讀取另受所選工作區、目錄及瀏覽器權限限制。",
    pending: "待確認瀏覽器",
    reviewLater: "稍後在遠端設定中處理",
    reviewLaterHint: "關閉視窗不會授權；請求仍可在遠端設定中處理，過期後自動失效。",
    decisionFailed: "處理失敗或請求已過期，請到遠端設定查看最新狀態。",
    devices: "已授權瀏覽器",
    verify: "請與瀏覽器核對驗證數字",
    send: "允許傳送",
    approve: "允許核准",
    manage: "允許新增及交接 Codex 任務",
    files: "允許查看授權目錄及產物",
    attachments: "允許上傳圖片與檔案",
    advancedControl: "允許執行中追加及原生佇列",
    organize: "允許重新命名及封存對話",
    settings: "允許修改任務模型及模式",
    extendedApproval: "允許原生延伸審批（含工作階段及永久規則）",
    accept: "確認授權",
    reject: "拒絕",
    revoke: "撤銷",
    empty: "暫無",
    running: "執行中",
    stopped: "已關閉",
    expires: "有效期限",
    loading: "正在讀取 Web 設定…",
    unavailable: "Web 設定無法使用",
    warning:
      "實驗功能僅在通過驗證的主機與對話上可用；停止僅表示中斷目前輪次，不保證背景命令已結束。",
    read: "歷史讀取",
  },
  "en-US": {
    generateAccess: "Generate 8-digit access code",
    codeScope:
      "A valid access code authorizes all AgentKib workspaces at the selected level without another desktop confirmation. Read-only allows session history and files; full remote access adds task control, approvals and uploads. Change the level or revoke access below at any time. Share only with trusted devices.",
    fullAccess: "Full remote access",
    readOnlyAccess: "Read-only (sessions and files)",
    accessLevel: "Access level",
    acceptance:
      "Isolated local acceptance: controls are limited to this session. This is not release approval.",
    portError: "This port is in use. Choose another port and save.",
    unverified:
      "Web experimental controls have not passed live acceptance in this build. Sending and approvals remain disabled.",
    title: "Allow phone access to this computer",
    enabled: "Enable local Web service",
    port: "Port",
    origin: "External HTTPS origin",
    experimental: "Enable experimental controls (browser grants are still required)",
    save: "Save settings",
    generate: "Generate 8-digit pairing code",
    scope:
      "History access includes all registered and future workspaces. Task management and file access additionally require the selected workspace, directory and browser permissions.",
    pending: "Pending browsers",
    reviewLater: "Review later in remote settings",
    reviewLaterHint:
      "Closing this dialog does not grant access. The request remains in remote settings until it expires.",
    decisionFailed: "The request failed or expired. Check its latest status in remote settings.",
    devices: "Authorized browsers",
    verify: "Compare these verification digits with the browser",
    send: "Allow sending",
    approve: "Allow approvals",
    manage: "Allow creating and handing off Codex tasks",
    files: "Allow authorized files and artifacts",
    attachments: "Upload images and files",
    advancedControl: "Steer running tasks and manage the native queue",
    organize: "Rename and archive sessions",
    settings: "Change task model and mode",
    extendedApproval: "Extended native approvals, including session and persistent rules",
    accept: "Authorize",
    reject: "Reject",
    revoke: "Revoke",
    empty: "None",
    running: "Running",
    stopped: "Disabled",
    expires: "Expires",
    loading: "Loading Web settings…",
    unavailable: "Web settings unavailable",
    warning:
      "Experimental controls require a verified host and session. Stopping interrupts a turn; background commands may still run.",
    read: "Read history",
  },
  "ja-JP": {
    generateAccess: "8 桁の認証コードを生成",
    codeScope:
      "有効な認証コードで、選択したレベルに応じて全 AgentKib ワークスペースへのアクセスを許可します。デスクトップでの再確認は不要です。「閲覧のみ」は会話履歴とファイルの閲覧、「完全なリモートアクセス」はタスク操作・承認・アップロードも含みます。レベルの変更や取り消しは下でいつでも行えます。信頼できる端末にのみ共有してください。",
    fullAccess: "完全なリモートアクセス",
    readOnlyAccess: "閲覧のみ（会話とファイル）",
    accessLevel: "アクセスレベル",
    acceptance:
      "ローカル検証モード：操作は次のセッションのみ対象です。正式な検証完了ではありません。",
    portError: "ポートは使用中です。別のポートを選択して保存してください。",
    unverified: "このビルドの Web 操作は実環境で未検証のため、送信と承認は無効です。",
    title: "スマートフォンからこのコンピューターにアクセス",
    enabled: "ローカル Web サービスを有効化",
    port: "ポート",
    origin: "外部 HTTPS アドレス",
    experimental: "実験的な操作を有効化（ブラウザーごとの権限も必要）",
    save: "設定を保存",
    generate: "8 桁のペアリングコードを生成",
    scope:
      "履歴の閲覧は登録済みおよび今後追加される全ワークスペースが対象です。タスク管理とファイル閲覧には、選択したワークスペース・ディレクトリとブラウザーの権限が別途必要です。",
    pending: "確認待ちのブラウザー",
    reviewLater: "後でリモート設定で確認",
    reviewLaterHint:
      "閉じてもアクセスは許可されません。リクエストは期限切れまでリモート設定に残ります。",
    decisionFailed: "処理に失敗したか期限切れです。リモート設定で最新の状態を確認してください。",
    devices: "認証済みブラウザー",
    verify: "ブラウザーに表示された確認番号と照合してください",
    send: "送信を許可",
    approve: "承認操作を許可",
    manage: "Codex タスクの作成と引き継ぎを許可",
    files: "許可済みファイルと成果物の閲覧を許可",
    attachments: "画像とファイルのアップロード",
    advancedControl: "実行中の追加指示とネイティブキュー",
    organize: "会話の名前変更とアーカイブ",
    settings: "タスクのモデルとモードの変更",
    extendedApproval: "拡張ネイティブ承認（セッション・永続ルールを含む）",
    accept: "アクセスを許可",
    reject: "拒否",
    revoke: "取り消す",
    empty: "なし",
    running: "稼働中",
    stopped: "無効",
    expires: "有効期限",
    loading: "Web 設定を読み込み中…",
    unavailable: "Web 設定を利用できません",
    warning:
      "実験的な操作は検証済みのホストと会話のみで利用できます。停止は現在のターンを中断します。",
    read: "履歴の閲覧",
  },
};
