/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionRouteImport } from './routes/_session'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as SessionPairRouteImport } from './routes/_session.pair'
import { Route as SessionSessionsRouteImport } from './routes/_session.sessions'
import { Route as SessionSessionsIndexRouteImport } from './routes/_session.sessions.index'
import { Route as SessionSessionsSessionIdRouteImport } from './routes/_session.sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/_session',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionPairRoute = SessionPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => SessionRoute,
} as any)
const SessionSessionsRoute = SessionSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => SessionRoute,
} as any)
const SessionSessionsIndexRoute = SessionSessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionSessionsRoute,
} as any)
const SessionSessionsSessionIdRoute =
  SessionSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => SessionSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/pair': typeof SessionPairRoute
  '/sessions': typeof SessionSessionsRouteWithChildren
  '/sessions/$sessionId': typeof SessionSessionsSessionIdRoute
  '/sessions/': typeof SessionSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/pair': typeof SessionPairRoute
  '/sessions/$sessionId': typeof SessionSessionsSessionIdRoute
  '/sessions': typeof SessionSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_session': typeof SessionRouteWithChildren
  '/connect': typeof ConnectRoute
  '/_session/pair': typeof SessionPairRoute
  '/_session/sessions': typeof SessionSessionsRouteWithChildren
  '/_session/sessions/$sessionId': typeof SessionSessionsSessionIdRoute
  '/_session/sessions/': typeof SessionSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/pair'
    | '/sessions'
    | '/sessions/$sessionId'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect' | '/pair' | '/sessions/$sessionId' | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/_session'
    | '/connect'
    | '/_session/pair'
    | '/_session/sessions'
    | '/_session/sessions/$sessionId'
    | '/_session/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SessionRoute: typeof SessionRouteWithChildren
  ConnectRoute: typeof ConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session': {
      id: '/_session'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session/pair': {
      id: '/_session/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof SessionPairRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_session/sessions': {
      id: '/_session/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionSessionsRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_session/sessions/': {
      id: '/_session/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionSessionsIndexRouteImport
      parentRoute: typeof SessionSessionsRoute
    }
    '/_session/sessions/$sessionId': {
      id: '/_session/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionSessionsSessionIdRouteImport
      parentRoute: typeof SessionSessionsRoute
    }
  }
}

interface SessionSessionsRouteChildren {
  SessionSessionsSessionIdRoute: typeof SessionSessionsSessionIdRoute
  SessionSessionsIndexRoute: typeof SessionSessionsIndexRoute
}

const SessionSessionsRouteChildren: SessionSessionsRouteChildren = {
  SessionSessionsSessionIdRoute: SessionSessionsSessionIdRoute,
  SessionSessionsIndexRoute: SessionSessionsIndexRoute,
}

const SessionSessionsRouteWithChildren = SessionSessionsRoute._addFileChildren(
  SessionSessionsRouteChildren,
)

interface SessionRouteChildren {
  SessionPairRoute: typeof SessionPairRoute
  SessionSessionsRoute: typeof SessionSessionsRouteWithChildren
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionPairRoute: SessionPairRoute,
  SessionSessionsRoute: SessionSessionsRouteWithChildren,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SessionRoute: SessionRouteWithChildren,
  ConnectRoute: ConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
