/** Native asset locations and descriptions from the existing scanner contract. */
export const ASSET_CANDIDATES: Record<string, readonly (readonly [string, string, string])[]> = {
  codex: [
    ["AGENTS.md", "instruction", "Codex project instructions"],
    [".agents/skills", "skill", "Shared Agent Skill"],
    [".codex/config.toml", "configuration", "Codex project configuration"],
    [".codex/agents", "agent", "Codex custom Agent"],
    [".codex/hooks.json", "hook", "Codex Hooks"],
  ],
  "claude-code": [
    ["CLAUDE.md", "instruction", "Claude Code project instructions"],
    [".claude/CLAUDE.md", "instruction", "Claude Code project instructions"],
    [".claude/rules", "instruction", "Claude Code directory rules"],
    [".claude/skills", "skill", "Claude Code Skills"],
    [".claude/agents", "agent", "Claude Code Subagents"],
    [".claude/settings.json", "configuration", "Claude Code settings"],
    [".mcp.json", "connection", "Claude Code MCP"],
  ],
  cursor: [
    ["AGENTS.md", "instruction", "Cursor project instructions"],
    [".cursor/rules", "instruction", "Cursor project rules"],
    [".cursor/commands", "instruction", "Cursor commands"],
    [".cursor/skills", "skill", "Cursor Skills"],
    [".agents/skills", "skill", "Shared Agent Skill"],
    [".cursor/hooks.json", "hook", "Cursor Hooks"],
    [".cursor/mcp.json", "connection", "Cursor MCP"],
  ],
  opencode: [
    ["AGENTS.md", "instruction", "OpenCode project instructions"],
    ["CLAUDE.md", "instruction", "OpenCode fallback project instructions"],
    ["opencode.json", "configuration", "OpenCode configuration"],
    ["opencode.jsonc", "configuration", "OpenCode configuration"],
    [".opencode/opencode.json", "connection", "OpenCode project configuration and MCP"],
    [".opencode/opencode.jsonc", "connection", "OpenCode project configuration and MCP"],
    [".opencode/skills", "skill", "OpenCode Skills"],
    [".claude/skills", "skill", "Claude-compatible Skills"],
    [".agents/skills", "skill", "Shared Agent Skill"],
    [".opencode/agents", "agent", "OpenCode custom Agents"],
    [".opencode/commands", "instruction", "OpenCode commands"],
    [".opencode/plugins", "configuration", "OpenCode plugins"],
    [".opencode/tools", "configuration", "OpenCode custom tools"],
  ],
  "open-claw": [
    ["AGENTS.md", "instruction", "OpenClaw workspace instructions"],
    ["SOUL.md", "instruction", "OpenClaw persona"],
    ["IDENTITY.md", "instruction", "OpenClaw identity"],
    ["USER.md", "memory", "OpenClaw user profile"],
    ["MEMORY.md", "memory", "OpenClaw long-term memory"],
    ["TOOLS.md", "configuration", "OpenClaw tool notes"],
    ["skills", "skill", "OpenClaw Workspace Skills"],
    [".agents/skills", "skill", "Shared Agent Skill"],
  ],
  hermes: [
    [".hermes.md", "instruction", "Hermes project instructions"],
    ["HERMES.md", "instruction", "Hermes project instructions"],
    ["AGENTS.md", "instruction", "Hermes-compatible project instructions"],
    ["CLAUDE.md", "instruction", "Hermes-compatible project instructions"],
    [".cursorrules", "instruction", "Hermes Cursor-compatible rules"],
  ],
  "grok-build": [
    ["AGENTS.md", "instruction", "Grok Build project instructions"],
    [".grok/rules", "instruction", "Grok Build project rules"],
    [".grok/skills", "skill", "Grok Build Skills"],
    [".grok/agents", "agent", "Grok Build Agents"],
    [".grok/plugins", "configuration", "Grok Build Plugins"],
    [".grok/hooks", "hook", "Grok Build Hooks"],
    [".grok/workflows", "configuration", "Grok Build Workflows"],
    [".grok/config.toml", "configuration", "Grok Build project configuration"],
    [".grok/lsp.json", "configuration", "Grok Build LSP configuration"],
  ],
  antigravity: [
    ["AGENTS.md", "instruction", "Antigravity project instructions"],
    ["GEMINI.md", "instruction", "Antigravity project instructions"],
    [".agents/rules", "instruction", "Antigravity workspace rules"],
    [".agent/rules", "instruction", "Antigravity workspace rules"],
    [".agents/plugins", "configuration", "Antigravity workspace plugins"],
    [".agents/skills", "skill", "Antigravity Skills"],
    [".agents/mcp_config.json", "connection", "Antigravity MCP"],
  ],
  "deepseek-harness": [
    ["AGENTS.md", "instruction", "DeepSeek Harness project instructions"],
    ["CLAUDE.md", "instruction", "DeepSeek Harness project instructions"],
    ["AGENTS.local.md", "instruction", "DeepSeek Harness local project instructions"],
    ["CLAUDE.local.md", "instruction", "DeepSeek Harness local project instructions"],
    [".dsh/skills", "skill", "DeepSeek Harness Skills"],
    [".agents/skills", "skill", "Shared Agent Skill"],
  ],
};
