// Shared schema 15 queries, kept equivalent to the existing store contracts.
export const INSIGHT_SQL = {
  summaryUsage:
    "SELECT COALESCE(SUM(u.total_tokens), 0) AS k0, COALESCE(SUM(u.input_tokens), 0) AS k1, COALESCE(SUM(u.output_tokens), 0) AS k2, COALESCE(SUM(u.cache_read_tokens + u.cache_write_tokens), 0) AS k3, COALESCE(SUM(u.reasoning_tokens), 0) AS k4, COALESCE(SUM(u.session_count), 0) AS k5 FROM usage_events u LEFT JOIN workspaces w ON w.id = u.workspace_id\n             WHERE (?1 IS NULL OR u.day >= ?1) AND (?2 IS NULL OR u.day <= ?2) AND (?3 IS NULL OR u.surface_agent = ?3) AND (?4 IS NULL OR u.workspace_id = ?4) AND (?5 IS NULL OR w.repository_group_id = ?5)",
  summaryCommits:
    "SELECT COALESCE(SUM(is_mine), 0) AS k0, COUNT(*) AS k1, COALESCE(SUM(EXISTS(SELECT 1 FROM commit_attributions a WHERE a.repository_group_id = c.repository_group_id AND a.commit_hash = c.commit_hash AND a.confidence = 'exact' AND (?4 IS NULL OR a.agent = ?4))), 0) AS k2 FROM git_commits c WHERE (?1 IS NULL OR c.day >= ?1) AND (?2 IS NULL OR c.day <= ?2) AND (?3 IS NULL OR c.repository_group_id = ?3)",
  heatmapUsage:
    "SELECT d.day AS k0, SUM(d.total_tokens) AS k1, SUM(d.session_count) AS k2, MAX(CASE d.quality WHEN 'incomplete' THEN 2 WHEN 'estimated' THEN 1 ELSE 0 END) AS k3 FROM usage_daily d LEFT JOIN workspaces w ON w.id = NULLIF(d.workspace_id, '')\n             WHERE d.day >= ?1 AND d.day <= ?2 AND (?3 IS NULL OR d.surface_agent = ?3) AND (?4 IS NULL OR d.workspace_id = ?4) AND (?5 IS NULL OR w.repository_group_id = ?5)\n             GROUP BY d.day",
  heatmapCommits:
    "SELECT c.day AS k0, SUM(c.is_mine) AS k1, COUNT(*) AS k2, SUM(EXISTS(SELECT 1 FROM commit_attributions a WHERE a.repository_group_id = c.repository_group_id AND a.commit_hash = c.commit_hash AND a.confidence = 'exact' AND (?4 IS NULL OR a.agent = ?4))) AS k3 FROM git_commits c WHERE c.day >= ?1 AND c.day <= ?2 AND (?3 IS NULL OR c.repository_group_id = ?3) GROUP BY c.day",
  agents:
    "SELECT u.surface_agent AS k0, SUM(u.total_tokens) AS k1, SUM(u.input_tokens) AS k2, SUM(u.output_tokens) AS k3, SUM(u.cache_read_tokens + u.cache_write_tokens) AS k4, SUM(u.reasoning_tokens) AS k5, SUM(u.session_count) AS k6, MAX(CASE u.quality WHEN 'incomplete' THEN 2 WHEN 'estimated' THEN 1 ELSE 0 END) AS k7 FROM usage_events u LEFT JOIN workspaces w ON w.id = u.workspace_id\n             WHERE (?1 IS NULL OR u.day >= ?1) AND (?2 IS NULL OR u.day <= ?2) AND (?3 IS NULL OR u.workspace_id = ?3) AND (?4 IS NULL OR w.repository_group_id = ?4)\n             GROUP BY u.surface_agent ORDER BY SUM(u.total_tokens) DESC",
  models:
    "SELECT COALESCE(NULLIF(u.model, ''), '__unknown_model__') AS k0, SUM(u.total_tokens) AS k1, SUM(u.session_count) AS k2 FROM usage_events u LEFT JOIN workspaces w ON w.id = u.workspace_id\n             WHERE (?1 IS NULL OR u.day >= ?1) AND (?2 IS NULL OR u.day <= ?2) AND (?3 IS NULL OR u.surface_agent = ?3) AND (?4 IS NULL OR u.workspace_id = ?4) AND (?5 IS NULL OR w.repository_group_id = ?5)\n             GROUP BY COALESCE(NULLIF(u.model, ''), '__unknown_model__') HAVING SUM(u.total_tokens) > 0 ORDER BY SUM(u.total_tokens) DESC LIMIT 20",
  workspaces:
    "SELECT u.workspace_id AS k0, COALESCE(w.name, '__unlinked_workspace__') AS k1, SUM(u.total_tokens) AS k2, SUM(u.session_count) AS k3 FROM usage_events u LEFT JOIN workspaces w ON w.id = u.workspace_id\n             WHERE (?1 IS NULL OR u.day >= ?1) AND (?2 IS NULL OR u.day <= ?2) AND (?3 IS NULL OR u.surface_agent = ?3) AND (?4 IS NULL OR u.workspace_id = ?4) AND (?5 IS NULL OR w.repository_group_id = ?5)\n             GROUP BY u.workspace_id, COALESCE(w.name, '__unlinked_workspace__') HAVING SUM(u.total_tokens) > 0 OR SUM(u.session_count) > 0 ORDER BY SUM(u.total_tokens) DESC LIMIT 20",
  activeUsage:
    "SELECT DISTINCT d.day AS k0 FROM usage_daily d LEFT JOIN workspaces w ON w.id = NULLIF(d.workspace_id, '')\n             WHERE (d.total_tokens > 0 OR d.session_count > 0) AND (?1 IS NULL OR d.day >= ?1) AND (?2 IS NULL OR d.day <= ?2) AND (?3 IS NULL OR d.surface_agent = ?3) AND (?4 IS NULL OR d.workspace_id = ?4) AND (?5 IS NULL OR w.repository_group_id = ?5)",
  activeCommits:
    "SELECT DISTINCT c.day AS k0 FROM git_commits c WHERE c.is_mine = 1 AND (?1 IS NULL OR c.day >= ?1) AND (?2 IS NULL OR c.day <= ?2) AND (?3 IS NULL OR c.repository_group_id = ?3) AND (?4 IS NULL OR EXISTS(SELECT 1 FROM commit_attributions a WHERE a.repository_group_id = c.repository_group_id AND a.commit_hash = c.commit_hash AND a.agent = ?4 AND a.confidence = 'exact'))",
  repositories:
    "SELECT c.repository_group_id AS k0, COALESCE((SELECT MIN(w.name) FROM workspaces w WHERE w.repository_group_id = c.repository_group_id), 'Repository') AS k1, SUM(c.is_mine) AS k2, COUNT(*) AS k3, SUM(EXISTS(SELECT 1 FROM commit_attributions a WHERE a.repository_group_id = c.repository_group_id AND a.commit_hash = c.commit_hash AND a.confidence = 'exact')) AS k4 FROM git_commits c\n             WHERE (?1 IS NULL OR c.day >= ?1) AND (?2 IS NULL OR c.day <= ?2) AND (?3 IS NULL OR c.repository_group_id = ?3)\n             GROUP BY c.repository_group_id ORDER BY SUM(c.is_mine) DESC",
  status:
    "SELECT provider AS k0, available AS k1, quality AS k2, coverage_from AS k3, coverage_to AS k4, imported_events AS k5, error AS k6, error_key AS k7, error_params AS k8, updated_at AS k9 FROM insight_cursors WHERE provider NOT LIKE 'git:%' ORDER BY provider",
  identities:
    "SELECT id AS k0, CASE\n                      WHEN source GLOB 'repository:*' THEN 'settings.gitIdentityRepository'\n                      WHEN source = 'git-global' THEN 'settings.gitIdentityGlobal'\n                      WHEN source = 'manual' THEN 'settings.gitIdentityAlias'\n                      ELSE label\n                    END AS label, source AS k2, enabled AS k3 FROM git_identities ORDER BY source, label",
  workspaceCount:
    "SELECT COUNT(DISTINCT workspace_id) AS k0 FROM usage_events WHERE workspace_id IS NOT NULL AND workspace_id != '' AND (total_tokens > 0 OR session_count > 0)",
} as const;
